name: pdff
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/koji-1009/pdff

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.pdff
        pluginClass: PdffPlugin
      ios:
        pluginClass: PdffPlugin
      web:
        pluginClass: PdffWeb
        fileName: pdff_web.dart
